name: barter_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  firebase_storage: ^11.0.9
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  image: ^3.2.2 
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_zoom_drawer: ^3.0.3
  syncfusion_flutter_charts: ^19.1.56
  hidden_drawer_menu: ^3.0.1
  firebase_database: ^10.0.9
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/